// Reference data for the fleet vehicle Make/Model/Type pickers (DR-096).
// Vehicle.make/model/vehicleType stay free-text in the schema (see
// prisma/schema.prisma's own comment on vehicleType -- deliberately
// open-ended, varies too much across NA/DRC/Zambia/Zimbabwe/Botswana for an enum);
// this is a curated *suggestion* list for the UI only, not a constraint --
// every picker built on this data always offers an "Other" escape hatch
// that accepts any free text, so a real vehicle the operator actually owns
// is never blocked from being entered just because it isn't listed here.
//
// Scoped to what a Southern/Central-African tourism operator's fleet
// plausibly contains -- 4x4s/pickups, guest-transfer sedans/vans, buses/
// coaches, support trucks, motorcycles/ATVs for adventure add-ons, and
// boats for river/lake activities (e.g. Chobe, Okavango, Zambezi) -- not
// an exhaustive list of every make sold worldwide (ultra-exotic brands
// like Ferrari/Lamborghini/Bentley are omitted as unrealistic fleet
// vehicles for this business, not an oversight).

export const VEHICLE_TYPES: string[] = [
  '4x4 / Off-Road',
  'ATV / Quad Bike',
  'Boat — Houseboat',
  'Boat — Speedboat',
  'Bus / Coach',
  'Hatchback',
  'Minibus / Minivan',
  'Motorcycle',
  'Panel Van',
  'Pickup Truck (Bakkie)',
  'Sedan',
  'SUV',
  'Trailer',
  'Truck',
  'Van',
];

export const VEHICLE_MAKES: string[] = [
  'Ashok Leyland',
  'Audi',
  'Bajaj',
  'BMW',
  'BMW Motorrad',
  'Boston Whaler',
  'BYD',
  'Can-Am',
  'Chevrolet',
  'Citroën',
  'Dacia',
  'DAF',
  'Evinrude',
  'Fiat',
  'Foton',
  'Ford',
  'GAC',
  'Golden Dragon',
  'GWM (Great Wall)',
  'Haval',
  'Hino',
  'Honda',
  'Honda Marine',
  'Hyundai',
  'Isuzu',
  'Iveco',
  'JAC',
  'Jeep',
  'Kawasaki',
  'Kia',
  'King Long',
  'KTM',
  'Land Rover',
  'Lexus',
  'Mahindra',
  'MAN',
  'Mazda',
  'Mercedes-Benz',
  'Mercury Marine',
  'Mitsubishi',
  'Nissan',
  'Opel',
  'Peugeot',
  'Polaris',
  'Renault',
  'Scania',
  'SEAT',
  'Škoda',
  'Ssangyong',
  'Subaru',
  'Suzuki',
  'Suzuki Marine',
  'Tata',
  'Tesla',
  'Toyota',
  'UD Trucks',
  'Volkswagen',
  'Volvo',
  'Yamaha',
  'Yamaha Marine',
  'Yutong',
];

// Curated per make -- deepest for the makes most likely to actually appear
// in a Namibia/DRC/Zambia/Zimbabwe tour fleet, thinner (or absent, falling
// back to Other-only) for makes included mainly for guest-transfer sedans
// or one-off support vehicles. Not filtered by vehicle Type -- a Make's
// model list is the same regardless of whether it's tagged 4x4/Sedan/Bus
// etc., since cross-referencing both would add real complexity for little
// practical benefit here.
export const VEHICLE_MODELS_BY_MAKE: Record<string, string[]> = {
  Toyota: [
    'Land Cruiser 70 Series',
    'Land Cruiser 300 Series',
    'Land Cruiser Prado',
    'Hilux',
    'Fortuner',
    'Hiace',
    'Quantum',
    'Corolla',
    'Corolla Cross',
    'Camry',
    'RAV4',
    'Yaris',
    'Avanza',
    'Coaster',
    'Dyna',
  ],
  'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Sport', 'Range Rover Evoque', 'Series III'],
  Nissan: ['Navara', 'Patrol', 'X-Trail', 'NP300 Hardbody', 'NV350 Urvan', 'Almera', 'Sentra', 'Terrano'],
  Ford: ['Ranger', 'Everest', 'Transit', 'Transit Custom', 'Focus', 'EcoSport', 'F-150'],
  Isuzu: ['D-Max', 'MU-X', 'KB', 'NPR', 'FRR'],
  Mitsubishi: ['Pajero', 'Pajero Sport', 'Triton', 'L200', 'Outlander', 'Fuso Canter'],
  Mahindra: ['Bolero', 'Scorpio', 'XUV500', 'Pik Up', 'Thar'],
  Tata: ['Xenon', 'Ace', 'LPT', 'Prima'],
  'GWM (Great Wall)': ['Steed', 'P-Series'],
  Haval: ['H6', 'Jolion'],
  Jeep: ['Wrangler', 'Grand Cherokee', 'Cherokee', 'Gladiator'],
  Suzuki: ['Jimny', 'Vitara', 'Grand Vitara', 'Swift', 'Ertiga', 'DR650'],
  Mazda: ['BT-50', 'CX-5', 'Mazda3'],
  Volkswagen: ['Amarok', 'Transporter', 'Crafter', 'Polo', 'Caddy'],
  Chevrolet: ['Trailblazer', 'Colorado', 'Spark'],
  Ssangyong: ['Musso', 'Rexton'],
  Tesla: ['Model 3', 'Model Y', 'Model S', 'Model X', 'Cybertruck'],
  Foton: ['Tunland'],
  JAC: ['T6', 'T8'],
  'Mercedes-Benz': ['Sprinter', 'G-Class', 'GLE', 'Vito', 'Actros'],
  BMW: ['X5', 'X3', '3 Series'],
  Audi: ['Q7', 'Q5', 'A4'],
  Lexus: ['LX', 'GX'],
  Hyundai: ['H-1', 'Tucson', 'Santa Fe', 'i10', 'Accent'],
  Kia: ['Sportage', 'Sorento', 'Rio'],
  Honda: ['CR-V', 'Civic', 'Fit', 'CRF', 'Africa Twin'],
  Renault: ['Duster', 'Kangoo', 'Master'],
  Peugeot: ['4008', 'Partner', 'Boxer'],
  Citroën: ['Berlingo', 'Jumper'],
  Opel: ['Corsa', 'Astra'],
  Fiat: ['Panda', 'Ducato'],
  Škoda: ['Octavia', 'Kodiaq'],
  SEAT: ['Ibiza', 'Ateca'],
  Dacia: ['Duster', 'Sandero'],
  Subaru: ['Forester', 'Outback'],
  Volvo: ['XC90', 'FH', 'B8R'],
  Iveco: ['Daily', 'Eurocargo'],
  MAN: ['TGX', "Lion's Coach"],
  Scania: ['R-Series', 'Touring'],
  DAF: ['XF'],
  Hino: ['300 Series', '500 Series'],
  'UD Trucks': ['Quon', 'Croner'],
  Yutong: ['ZK6122'],
  'King Long': ['XMQ6127'],
  'Golden Dragon': ['XML6127'],
  'Ashok Leyland': ['Falcon', 'Viking'],
  Yamaha: ['XT250', 'Ténéré 700'],
  Kawasaki: ['KLR650', 'Versys'],
  KTM: ['390 Adventure', '890 Adventure'],
  'BMW Motorrad': ['R 1250 GS', 'F 850 GS'],
  Polaris: ['Ranger', 'Sportsman'],
  'Can-Am': ['Outlander', 'Defender'],
  Bajaj: ['Boxer', 'Pulsar'],
  'Yamaha Marine': ['F115', 'F300'],
  'Suzuki Marine': ['DF140', 'DF350A'],
  'Mercury Marine': ['FourStroke 150', 'Verado'],
  'Honda Marine': ['BF150', 'BF250'],
  Evinrude: ['E-TEC G2'],
  'Boston Whaler': ['Montauk', 'Outrage'],
  BYD: ['Song Plus', 'Dolphin', 'Han'],
};
